language: node_js
cache: npm

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

stages:
  - test
  - name: release
    if: branch = master AND type IN (push)

jobs:
  include:
    - stage: test
      node_js: 12
      script: npm run test
    - node_js: 8
      script: npm run test
    - node_js: 10
      env: Node 10, coverage upload
      script:
        - npm run test
        - npm run coverage:upload
    - node_js: lts/*
      addons:
        apt:
          packages:
            # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
            - libgconf-2-4
      env: browser tests
      script:
        - npm run test:browser
    - node_js: lts/*
      sudo: required
      addons:
        chrome: stable
      env: bundle size
      script:
        - npm run build
        - npx bundlesize

    # release stage: run semantic release & update the docs
    - stage: release
      node_js: lts/*
      env: semantic-release
      script:
        - npm run build
        - npm run bundle-report
        - npx semantic-release
