language: node_js
cache: npm

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

stages:
  - test
  - name: release
    if: branch = master AND type IN (push)

jobs:
  include:
    - node_js: 8
      script: npm run test
    - node_js: 10
      script: npm run test
    - node_js: 12
      script: npm run test

    # release stage: run semantic release & update the docs
    - stage: release
      node_js: lts/*
      env: semantic-release
      script:
        - npm run build
        - npx semantic-release
